apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/disk
  labels:
    testing.upbound.io/example-name: disk
  name: diskgcp
spec:
  forProvider:
    labels:
      environment: dev
    physicalBlockSizeBytes: 4096
    type: pd-ssd
    zone: us-central1-a
